# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: telefonica
    steps:
      # Example of scanning current branch for vulnerabilities, and put the results in the wiki of this rep
      - name: scan repo for leaked passwords and credentials
        run:  ' curl  -H "Content-Type: application/json"   -X POST "http://epg-trivy.hi.inet:5000/v1/scan-terraform?token=fb1d3b71-2c1e-49cb-b04b-54534534ef0a&update_wiki=true&repository=${GITHUB_REPOSITORY}&output_format=markdown&branch=${GITHUB_REF##*/}" '
